# Generated by Django 2.2 on 2020-02-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0002_auto_20200209_1529'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
