# Generated by Django 2.2 on 2020-02-02 09:59

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='文章内容'),
        ),
    ]
