# Generated by Django 2.2 on 2020-02-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200202_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-created_at',), 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
